# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import news_pb2 as proto_dot_news__pb2


class ProxyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getScraperData = channel.unary_unary(
                '/Proxy/getScraperData',
                request_serializer=proto_dot_news__pb2.ScraperDataRequest.SerializeToString,
                response_deserializer=proto_dot_news__pb2.ScraperResponse.FromString,
                )


class ProxyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getScraperData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getScraperData': grpc.unary_unary_rpc_method_handler(
                    servicer.getScraperData,
                    request_deserializer=proto_dot_news__pb2.ScraperDataRequest.FromString,
                    response_serializer=proto_dot_news__pb2.ScraperResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Proxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Proxy(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getScraperData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Proxy/getScraperData',
            proto_dot_news__pb2.ScraperDataRequest.SerializeToString,
            proto_dot_news__pb2.ScraperResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
